apiVersion: v1
kind: Service
metadata:
  name: cindr-postgres
  labels: { app: cindr-postgres }
spec:
  selector: { app: cindr-postgres }
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  clusterIP: None
